KR_Choksey/Controllers/LPController.cs
using KR_Choksey.Global;
using KR_Choksey.Models;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Data.SqlClient;
using System.IO;
using System.Linq;
using System.Text.RegularExpressions;
using System.Web;
using System.Web.Mvc;

namespace KR_Choksey.Controllers
{
    public class LPController : Controller
    {

        #region SIP (Get)

        [HttpGet]
        public ActionResult SIP()
        {
            //System.Web.HttpContext.Current.Session["SIPContRetUrl"] = Convert.ToString(Session["ReturnUrl"]);
            return View();
        }

        #endregion


        #region SIP (Post)

        [HttpPost]
        //public string SIP(string Name, string EmailId, string PhoneNumber, string QuickTopic, string Aadhar_Pan, string PMutualFund, string PInsurance, string PFinancialPlanning, string PIFund, string PIPms, string PIBrokerage, string PILend, string PIHold, string PSubBrokerage)
        public ActionResult SIP(string Name, string EmailId, string PhoneNumber, string QuickTopic, string Aadhar_Pan, string PMutualFund, string PInsurance, string PFinancialPlanning, string PIFund, string PIPms, string PIBrokerage, string PILend, string PIHold, string PSubBrokerage)
        //public ActionResult SIP(KrcSIPContacts objQC)
        {
            GlobalFunction objGFunc = new GlobalFunction();
            string result = "";
            KrcQuickContacts objContact = new KrcQuickContacts();
            string ReturnUrl = Convert.ToString(Session["ReturnUrl"]);
            System.Web.HttpContext.Current.Session["SIPContRetUrl"] = ReturnUrl;

            string EMMutualFund = "";
            string EMInsurance = "";
            string EMFinancialPlanning = "";
            string EMIFund = "";
            string EMIPms = "";
            string EMIBrokerage = "";
            string EMILend = "";
            string EMIHold = "";
            string EMSubBrokerage = "";

            if (!String.IsNullOrEmpty(Request.Form["g-recaptcha-response"]))
            {
                try
                {
                    string Products = "";
                    // Mutual Fund
                    if (PMutualFund == null)
                    {
                        PMutualFund = "";
                    }
                    if (PMutualFund != "")
                    {
                        if (PMutualFund != "false")
                        {
                            Products = Products + PMutualFund;
                            EMMutualFund = "fp@XXXXXXX.XXX";
                        }
                    }

                    // Insurance
                    if (PInsurance == null)
                    {
                        PInsurance = "";
                    }
                    if (PInsurance != "")
                    {
                        if (PInsurance != "false")
                        {
                            Products = Products + PInsurance;
                            EMInsurance = "fp@XXXXXXX.XXX";
                        }
                    }

                    // Financial Planning
                    if (PFinancialPlanning == null)
                    {
                        PFinancialPlanning = "";
                    }
                    if (PFinancialPlanning != "")
                    {
                        if (PFinancialPlanning != "false")
                        {
                            Products = Products + PFinancialPlanning;
                            EMFinancialPlanning = "fp@XXXXXXX.XXX";
                        }
                    }


                    // I Fund
                    if (PIFund == null)
                    {
                        PIFund = "";
                    }
                    if (PIFund != "")
                    {
                        if (PIFund != "false")
                        {
                            Products = Products + PIFund;
                            EMIFund = "ifund@XXXXXXX.XXX";
                        }
                    }


                    // I Pms
                    if (PIPms == null)
                    {
                        PIPms = "";
                    }
                    if (PIPms != "")
                    {
                        if (PIPms != "false")
                        {
                            Products = Products + PIPms;
                            EMIPms = "pmsclient@XXXXXXX.XXX";
                        }
                    }


                    // I Brokerage
                    if (PIBrokerage == null)
                    {
                        PIBrokerage = "";
                    }
                    if (PIBrokerage != "")
                    {
                        if (PIBrokerage != "false")
                        {
                            Products = Products + PIBrokerage;
                            EMIBrokerage = "prahsant.shah@XXXXXXX.XXX";
                        }
                    }


                    // I Lend
                    if (PILend == null)
                    {
                        PILend = "";
                    }
                    if (PILend != "")
                    {
                        if (PILend != "false")
                        {
                            Products = Products + PILend;
                            EMILend = "rahul.pandit@XXXXXXX.XXX";
                        }
                    }


                    // I Hold
                    if (PIHold == null)
                    {
                        PIHold = "";
                    }
                    if (PIHold != "")
                    {
                        if (PIHold != "false")
                        {
                            Products = Products + PIHold;
                            EMIHold = "mona.zaveri@XXXXXXX.XXX";
                        }
                    }


                    // Sub Brokerage
                    if (PSubBrokerage == null)
                    {
                        PSubBrokerage = "";
                    }
                    if (PSubBrokerage != "")
                    {
                        if (PSubBrokerage != "false")
                        {
                            Products = Products + PSubBrokerage;
                            EMSubBrokerage = "npcare@XXXXXXX.XXX";
                        }
                    }

                    if (Aadhar_Pan == null)
                    {
                        Aadhar_Pan = "";
                    }
                    if (QuickTopic == null)
                    {
                        QuickTopic = "";
                    }

                    objContact.Name = Name;
                    objContact.EmailId = EmailId;
                    objContact.PhoneNumber = PhoneNumber;
                    objContact.QuickTopic = QuickTopic;
                    objContact.Aadhar_PAN = Aadhar_Pan;

                    if (objContact.PhoneNumber.Length != 10)
                    {
                        result = "Enter Valid 10 Digit Mobile Number!";
                    }
                    else if (IsValidEmail(objContact.EmailId) == false)
                    {
                        //result = "Enter Valid Email Address!";
                        @ViewBag.HideClass = "alert alert-danger";
                        @ViewBag.Message = "Enter Valid Email Address";
                    }
                    else
                    {

                        if (ModelState.IsValid)
                        {
                            bool res = true;
                            foreach (char c in objContact.PhoneNumber)
                            {
                                if (c < '0' || c > '9')
                                {
                                    res = false;
                                }
                            }

                            if (res == false || (objContact.PhoneNumber.ToString().Length != 10))
                            {
                                @ViewBag.HideClass = "alert alert-danger";
                                @ViewBag.Message = "Please Enter Valid Mobile Number.";
                                result = "Please Enter Valid Mobile Number.";
                            }
                            else
                            {
                                try
                                {
                                    // Insertion Code For QuickContact Table //
                                    gConnection.Open();
                                    string sqlstr = "insert into KrcQuickContacts(Name,EmailId,PhoneNumber,QuickTopic,Screen,CreatedBy,CreatedOn,Products,Aadhar_PAN)";
                                    sqlstr = sqlstr + " values (@QuickContactName,@QuickContactEmail,@QuickContactPhone,@QuickContactMessage,@Screen,@CreatedBy,GetDate(),@Products,@Aadhar_PAN)";
                                    //cmd.CommandText = sqlstr;
                                    SqlCommand cmd = new SqlCommand(sqlstr, GlobalVariables.gConn);
                                    cmd.Parameters.Clear();
                                    cmd.Parameters.AddWithValue("@QuickContactName", objContact.Name);
                                    cmd.Parameters.AddWithValue("@QuickContactEmail", objContact.EmailId);
                                    cmd.Parameters.AddWithValue("@QuickContactPhone", objContact.PhoneNumber);
                                    cmd.Parameters.AddWithValue("@QuickContactMessage", objContact.QuickTopic);
                                    cmd.Parameters.AddWithValue("@Screen", ReturnUrl);
                                    cmd.Parameters.AddWithValue("@CreatedBy", "Online");
                                    cmd.Parameters.AddWithValue("@Products", Products);
                                    cmd.Parameters.AddWithValue("@Aadhar_Pan", objContact.Aadhar_PAN);

KR_Choksey/Views/LP/IEquity.cshtml
@model KR_Choksey.Models.KrcSIPContacts
@{
    ViewBag.Title = "iEquity | KRChoksey";
    Layout = "~/Views/Shared/_LayoutLP.cshtml";
    //Layout = null;
}

@*<script src="~/Scripts/DevJS/CommonTextBoxValidations.js"></script>*@
<script src="~/Content/js/jquery-1.11.1.min.js"></script>
<script src="~/Content/js/jquery.min.js"></script>

<script src="https://www.google.com/recaptcha/api.js" async="async" defer="defer"></script>

@using (Html.BeginForm("IEquity", "LP", FormMethod.Post, new { @class = "contact_page4" }))
{
    <div style="text-align:center" class="@ViewBag.HideClass"> 
        @ViewBag.Message
    </div>
    <!------------------------------ mid_body Section ------------------------------>
    <section id="mid_body">
        <section id="inner_page">
            <section id="inner_banner">
                <div class="main_image clearfix">
                    <div class="slider_text sip_invest clearfix">
                        <div class="slider_dd_content clearfix">
                            <h1 class="wow evnt_pakg fadeInUp animated" data-wow-duration="350ms" data-wow-delay="150ms">I-equity</h1>
                            <h5 class="wow evnt_pakg fadeInUp animated" data-wow-duration="800ms" data-wow-delay="450ms">investment strategy</h5>
                        </div>
                    </div>
                    <img src="~/Content/images/inner-banner-bg.jpg" alt="Inner banner bg" title="Inner banner bg">
                </div>
            </section>
            <section id="interoduction_sec">
                <article class="dd_dc_page clearfix">
                    <article class="interoduction_sec_box clearfix wow evnt_pakg fadeInUp animated" data-wow-duration="700ms" data-wow-delay="500ms">
                        <article class="mutual_fund_page_l clearfix"><img src="~/Content/images/i-equity-landing-image.jpg" alt="i equity landing image" title="i equity landing image"></article>
                        <article class="mutual_fund_page_l clearfix">
                            <div class="field_sec_box clearfix">
                                @*<input type="text" placeholder="Your Name *" value="" />*@
                                @Html.TextBoxFor(model => model.Name, null, new { placeholder = "Your Name *", id = "Name" })
                                @Html.ValidationMessageFor(model => model.Name, null, new { @class = "alert-danger" })
                            </div>
                            <div class="field_sec_box clearfix">
                                @*<input type="text" placeholder="Email Address *" value="" />*@
                                @Html.TextBoxFor(model => model.EmailId, null, new { placeholder = "Email Address *", id = "EmailId" })
                                @Html.ValidationMessageFor(model => model.EmailId, null, new { @class = "alert-danger" })
                            </div>
                            <div class="field_sec_box clearfix">
                                @*<input type="text" placeholder="Mobile Number *" value="" />*@
                                @Html.TextBoxFor(model => model.PhoneNumber, null, new { @class = "number", placeholder = "Mobile Number *", maxlength = 10, id = "Mobile" })
                                @Html.ValidationMessageFor(model => model.PhoneNumber, null, new { @class = "alert-danger" })
                            </div>
                            <div class="field_sec_box clearfix">
                                @*<input type="text" placeholder="Aadhar Number / PAN Number *" value="" />*@
                                @Html.TextBoxFor(model => model.Aadhar_PAN, null, new { @class = "number", placeholder = "Aadhar Number / PAN Number ", maxlength = 40, id = "Aadhar_PAN" })
                                @Html.ValidationMessageFor(model => model.Aadhar_PAN, null, new { @class = "alert-danger" })
                            </div>
                            <div class="field_sec_box clearfix">
                                @*<textarea name="Message" cols="" rows="" placeholder="Any Query"></textarea>*@
                                @Html.TextAreaFor(model => model.QuickTopic, new { placeholder = "Any Query", id = "AnyQuery" })
                                @Html.ValidationMessageFor(model => model.QuickTopic, null, new { @class = "alert-danger" })
                            </div>

                            <div class="field_sec_box clearfix">
                                <div class="pop_form clearfix">
                                    <label> <input style="width:auto !important;" name="PMutualFund" id="MutualFundID" type="checkbox" value="MutualFund"> Mutual Fund</label>
                                </div>

                                <div class="pop_form clearfix">
                                    <label> <input style="width:auto !important;" name="PInsurance" id="Insurance" type="checkbox" value="Insurance"> Insurance</label>
                                </div>

                                <div class="pop_form clearfix">
                                    <label> <input style="width:auto !important;" name="PFinancialPlanning" id="FinancialPlanning" type="checkbox" value="FinancialPlanning"> Financial Planning</label>
                                </div>

                                <div class="pop_form clearfix">
                                    <label> <input style="width:auto !important;" name="PIFund" id="IFund" type="checkbox" value="IFund"> i-fund</label>
                                </div>

                                <div class="pop_form clearfix">
                                    <label> <input style="width:auto !important;" name="PIPms" id="IPms" type="checkbox" value="IPms">i-PMS</label>
                                </div>

                                <div class="pop_form clearfix">
                                    <label> <input style="width:auto !important;" name="PIBrokerage" id="IBrokerage" type="checkbox" value="IBrokerage">i-Brokerage</label>
                                </div>

                                <div class="pop_form clearfix">
                                    <label> <input style="width:auto !important;" name="PILend" id="ILend" type="checkbox" value="ILend">i-Lend</label>
                                </div>

                                <div class="pop_form clearfix">
                                    <label> <input style="width:auto !important;" name="PIHold" id="IHold" type="checkbox" value="IHold">i-Hold (Demat)</label>
                                </div>

                                <div class="pop_form clearfix">
                                    <label> <input style="width:auto !important;" name="PSubBrokerage" id="SubBrokerage" type="checkbox" value="SubBrokerage">Sub Brokerage</label>
                                </div>

                            </div>

                            <div class="field_sec_box clearfix">
                                <div id="dvCaptcha" class="g-recaptcha" data-sitekey="6Lc_UQsUAAAAAKH_61ap6Yu3AMPi8MQX_8nV94u9"></div>
                            </div>

                            <div class="field_sec_box clearfix">
                                @*<input value="submit" type="button" onclick="QuickPost();">*@
                                @*<input value="submit" type="submit" >*@
                                @*<input id="Contact" value="Submit" type="button" style="width:100%;background-color:#f7901e;color:white" onclick="QuickPost();">*@
                                <input id="Contact" value="Submit" type="submit" style="width:100%;background-color:#f7901e;color:white">
                            </div>
                        </article>
                    </article>
                </article>
            </section>

            <section id="interoduction_sec">
                <article class="interoduction_sec_box clearfix wow evnt_pakg fadeInUp animated" data-wow-duration="700ms" data-wow-delay="500ms">
                    <p>Equity trading gives you the option to grow your investments with the market dynamics. It can fulfill your short-term as well as long-term financial goals, depending on your needs. At KRChoksey, our expert advisers will always guide you on the best scripts and the investment timing in order to book profits and minimize risks market volatility risks.</p>
                </article>
            </section>

            <section id="interoduction_sec">
                <article class="interoduction_sec_box">
                    <article class="sip_invest clearfix">
                        <div class="heading wow evnt_pakg fadeInUp animated" data-wow-duration="300ms" data-wow-delay="500ms">
                            <h2>Why invest in <span>i-equity</span></h2>
                        </div>
                        <div class="choksey_contt_sec clearfix wow evnt_pakg fadeInUp animated" data-wow-duration="600ms" data-wow-delay="800ms">
                            <p>Investment in equity in neccesary to beat inflation, historically equity has given supirior return in contrast to Fixed deposit, gold or real estate.</p>
                        </div>
                    </article>
                </article>
            </section>

            <section id="interoduction_sec">
                <article class="interoduction_sec_box">
                    <article class="sip_invest clearfix">
                        <div class="heading wow evnt_pakg fadeInUp animated" data-wow-duration="300ms" data-wow-delay="500ms">
                            <h2>Why invest <span>with KRChoksey?</span></h2>
                        </div>
                        <div class="choksey_contt_sec clearfix wow evnt_pakg fadeInUp animated" data-wow-duration="600ms" data-wow-delay="800ms">
                            <p>KR Choksey has proven track record of creation of wealth for thousands of  Investors. KR Choksey believe in providing personal service to clients &  transparency in trade. It also provides</p>
                            <ul>
                                <li>Online and offline trading solutions with value-added tools & services</li>
                                <li>Instant notifications about news, results, company updates and calls</li>
                                <li>Lower transaction costs</li>
                                <li>Online research and support</li>
                            </ul>
                        </div>
                    </article>
                </article>
            </section>

            <section id="interoduction_sec">
                <article class="interoduction_sec_box">
                    <article class="sip_invest clearfix">
                        <div class="heading wow evnt_pakg fadeInUp animated" data-wow-duration="300ms" data-wow-delay="500ms">
                            <h2>What is the  <span>investment approach?</span></h2>
                        </div>
                        <div class="choksey_contt_sec clearfix wow evnt_pakg fadeInUp animated" data-wow-duration="600ms" data-wow-delay="800ms">
                            <p>KR Choksey invest money on basis of fundamental of the company. We have a strong team of research who regularly visit various companies for making investment decision.</p>
                        </div>
                    </article>
                </article>
            </section>

            <section id="interoduction_sec">
                <article class="interoduction_sec_box">
                    <article class="sip_invest clearfix">
                        <div class="heading wow evnt_pakg fadeInUp animated" data-wow-duration="300ms" data-wow-delay="500ms">
                            <h2>What is the <span>past performance of the company</span></h2>
                        </div>
                        <div class="choksey_contt_sec clearfix wow evnt_pakg fadeInUp animated" data-wow-duration="600ms" data-wow-delay="800ms">
                            <p>Chairman of the company Kisanbhai has created wealth for thousands of investors. In 1990 era, Kisanbhai recommended stocks which have grown at a multiple pace such as Dr reddy lab , Bajaj Auto , Cipla , Madras Cement ,Finolex Cable, Supreme Industries, Acc, Ambuja cement, Sundaram fastner etc.</p>
                        </div>
                    </article>
                </article>
            </section>



            <section id="interoduction_sec">
                <article class="orange_bg clearfix wow evnt_pakg fadeInUp animated" data-wow-duration="1100ms" data-wow-delay="900ms">
                    <article class="interoduction_sec_box clearfix">
                        <h3>In case you have any queries in above matters, you may send us a mail at</h3>
                        <h2>service@XXXXXXX.XXX</h2>
                        <h3>or call us at</h3>
                        <h2>022-66965523</h2>
                    </article>
                </article>
            </section>

            <section id="interoduction_sec">
                <article class="manage_bg clearfix wow evnt_pakg fadeInUp animated" data-wow-duration="1100ms" data-wow-delay="900ms">
                    <article class="interoduction_sec_box orange_service clearfix">
                        <h2>we manage! <span>you earn!</span></h2>
                    </article>
                </article>
            </section>



        </section>
    </section>


    


}