KR_Choksey/Controllers/OnlineCMOTSApiController.cs
using KR_Choksey.Global;
using KR_Choksey.Models;
using System;
using System.Collections.Generic;
using System.Data.SqlClient;
using System.Linq;
using System.Text;
using System.Web;
using System.Web.Mvc;

namespace KR_Choksey.Controllers
{
    public class OnlineCMOTSApiController : Controller
    {

        #region Get BSE Online Data

        [HttpGet]       
        //[AllowCrossSiteJson]
        public ActionResult GetBSEData()
        {
            return View();
        }


        [HttpPost]
        public ActionResult GetBSEData(string lname, string currprice, string currtime, string prevclose)
        {
            try
            {
                bool result = false;
                gConnection.Open();
                string sqlstr = "select AutoId,lname ,currprice,currtime ,prevclose from BSEOnlinePrice where ";
                sqlstr = sqlstr + " lname = @lname and @currprice=@currprice and currtime=@currtime";
                SqlCommand cmd = new SqlCommand(sqlstr, GlobalVariables.gConn);
                cmd.Parameters.AddWithValue("@lname", lname);
                cmd.Parameters.AddWithValue("@currprice", currprice);
                cmd.Parameters.AddWithValue("@currtime", currtime);
                SqlDataReader sdr = cmd.ExecuteReader();
                while (sdr.Read())
                {
                    result = true;
                }
                sdr.Close();
                if (result == false)
                {
                    sqlstr = "Insert Into BSEOnlinePrice (lname ,currprice,currtime ,prevclose) ";
                    sqlstr = sqlstr + " values (@lname ,@currprice,@currtime ,@prevclose)";
                    cmd.Parameters.Clear();
                    cmd.CommandText = sqlstr;
                    cmd.Parameters.AddWithValue("@lname", lname);
                    cmd.Parameters.AddWithValue("@currprice", currprice);
                    cmd.Parameters.AddWithValue("@currtime", currtime);
                    cmd.Parameters.AddWithValue("@prevclose", prevclose);
                    cmd.ExecuteNonQuery();
                }
                gConnection.Close();
            }
            catch (Exception ex)
            {

            }
            return View();
        }


        #endregion
        

        #region Get NSE Online Data

        [HttpGet]
        //[AllowCrossSiteJson]
        public ActionResult GetNSEData()
        {
            return View();
        }


        [HttpPost]
        public ActionResult GetNSEData(string lname, string currprice, string currtime, string prevclose)
        {
            try
            {
                bool result = false;
                gConnection.Open();
                string sqlstr = "select AutoId,lname ,currprice,currtime ,prevclose from NSEOnlinePrice where ";
                sqlstr = sqlstr + " lname = @lname and @currprice=@currprice and currtime=@currtime";
                SqlCommand cmd = new SqlCommand(sqlstr, GlobalVariables.gConn);
                cmd.Parameters.AddWithValue("@lname", lname);
                cmd.Parameters.AddWithValue("@currprice", currprice);
                cmd.Parameters.AddWithValue("@currtime", currtime);
                SqlDataReader sdr = cmd.ExecuteReader();
                while(sdr.Read())
                {
                    result = true;
                }
                sdr.Close();
                if(result == false)
                {
                    sqlstr = "Insert Into NSEOnlinePrice (lname ,currprice,currtime ,prevclose) ";
                    sqlstr = sqlstr + " values (@lname ,@currprice,@currtime ,@prevclose)";
                    cmd.Parameters.Clear();
                    cmd.CommandText = sqlstr;
                    cmd.Parameters.AddWithValue("@lname", lname);
                    cmd.Parameters.AddWithValue("@currprice", currprice);
                    cmd.Parameters.AddWithValue("@currtime", currtime);
                    cmd.Parameters.AddWithValue("@prevclose", prevclose);
                    cmd.ExecuteNonQuery();
                }
                gConnection.Close();
            }
            catch (Exception ex)
            {

            }

                return View();
        }

        #endregion




        #region NSE Price Gainers Data

        [HttpGet]
        public ActionResult GetNSENetPriceGainersData()
        {
            return View();
        }


        [HttpPost]
        public ActionResult GetNSENetPriceGainersData(string result1)
        {
            try
            {
                bool result = false;
                List<NSENetPriceGainersData> objGrpList = new List<NSENetPriceGainersData>();
                var objects = Newtonsoft.Json.Linq.JArray.Parse(result1);

                foreach (Newtonsoft.Json.Linq.JObject root in objects)
                {
                    NSENetPriceGainersData objNSE = new NSENetPriceGainersData();
                    foreach (KeyValuePair<String, Newtonsoft.Json.Linq.JToken> app in root)
                    {

                        var appName = app.Key.ToString();
                        if (appName.ToUpper() == "stk_exchng".ToUpper())
                        {
                            objNSE.stk_exchng = app.Value.ToString();
                        }
                        else if (appName.ToUpper() == "sc_code".ToUpper())
                        {
                            objNSE.sc_code = app.Value.ToString();
                        }
                        else if (appName.ToUpper() == "co_code".ToUpper())
                        {
                            objNSE.co_code = app.Value.ToString();
                        }
                        else if (appName.ToUpper() == "symbol".ToUpper())
                        {
                            objNSE.symbol = app.Value.ToString();
                        }
                        else if (appName.ToUpper() == "isin".ToUpper())
                        {
                            objNSE.isin = app.Value.ToString();
                        }
                        else if (appName.ToUpper() == "co_name".ToUpper())
                        {
                            objNSE.co_name = app.Value.ToString();
                        }
                        else if (appName.ToUpper() == "sc_group".ToUpper())
                        {
                            objNSE.sc_group = app.Value.ToString();
                        }
                        else if (appName.ToUpper() == "upd_time".ToUpper())
                        {
                            objNSE.upd_time = Convert.ToDateTime(app.Value.ToString());
                        }
                        else if (appName.ToUpper() == "open_price".ToUpper())
                        {
                            objNSE.open_price = app.Value.ToString();
                        }
                        else if (appName.ToUpper() == "high_price".ToUpper())
                        {
                            objNSE.high_price = app.Value.ToString();
                        }
                        else if (appName.ToUpper() == "low_price".ToUpper())
                        {
                            objNSE.low_price = app.Value.ToString();
                        }
                        else if (appName.ToUpper() == "close_price".ToUpper())
                        {
                            objNSE.close_price = app.Value.ToString();
                        }
                        else if (appName.ToUpper() == "bbuy_qty".ToUpper())
                        {
                            objNSE.bbuy_qty = app.Value.ToString();
                        }
                        else if (appName.ToUpper() == "bbuy_price".ToUpper())
                        {
                            objNSE.bbuy_price = app.Value.ToString();
                        }
                        else if (appName.ToUpper() == "bsell_qty".ToUpper())
                        {
                            objNSE.bsell_qty = app.Value.ToString();
                        }
                        else if (appName.ToUpper() == "bsell_price".ToUpper())
                        {
                            objNSE.bsell_price = app.Value.ToString();
                        }
                        else if (appName.ToUpper() == "Prevclose".ToUpper())
                        {
                            objNSE.Prevclose = app.Value.ToString();
                        }
                        else if (appName.ToUpper() == "Perchg".ToUpper())
                        {
                            objNSE.Perchg = app.Value.ToString();
                        }
                        else if (appName.ToUpper() == "Netchg".ToUpper())
                        {
                            objNSE.Netchg = app.Value.ToString();
                        }
                        else if (appName.ToUpper() == "vol_traded".ToUpper())
                        {
                            objNSE.vol_traded = app.Value.ToString();
                        }
                        else if (appName.ToUpper() == "pervol".ToUpper())
                        {
                            objNSE.pervol = app.Value.ToString();
                        }
                        else if (appName.ToUpper() == "val_traded".ToUpper())
                        {
                            objNSE.val_traded = app.Value.ToString();

                        }
                        else if (appName.ToUpper() == "fiftytwoweekhigh".ToUpper())
                        {
                            objNSE.fiftytwoweekhigh = app.Value.ToString();
                        }
                        else if (appName.ToUpper() == "fiftytwoweeklow".ToUpper())
                        {
                            objNSE.fiftytwoweeklow = app.Value.ToString();
                        }
                        else if (appName.ToUpper() == "prev_vol_traded".ToUpper())
                        {

KR_Choksey/Views/OnlineCMOTSApi/GetBSEData.cshtml
@{
    ViewBag.Title = "GetBSEData";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>GetBSEData</h2>

@using (Html.BeginForm("GetBSEData", "OnlineCMOTSApi", FormMethod.Post, new { @class = "form-horizontal", role = "form", enctype = "multipart/form-data" }))
{

    <div class="jumbotron">
        @*<h1>ASP.NET</h1>
            <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
            <p><a href="http://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>*@
    </div>

    <div class="row">

        <input type="text" id="Mobile" name="Mobile" />

        <input type="submit" id="Post" name="Post" />

        <input type="text" name="lname" id="lname" />
        <input type="text" name="currprice" id="currprice" />
        <input type="text" name="currtime" id="currtime" />
        <input type="text" name="prevclose" id="prevclose" />

    </div>


    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/Scripts/jquery-1.10.2.js"></script>

    <script type="text/javascript">
    $(document).ready(function () {

        myFunc();

        function myFunc() {


            $.ajax(
      {
          type: 'GET',
          url: "http://krchokseyapi.cmlinks.com/Equity/Equity.svc/IntradayChart/SENSEX",
          data: { responsetype: "json" },
          success: function (response) {
              //alert(response);
              var result = response.slice(83, -4);
              //alert(result);
              $("#Mobile").val(result);

              $.each($.parseJSON(result), function (idx, obj) {
                  //alert(obj.lname);
                  $("#lname").val(obj.lname);
                  $("#currprice").val(obj.currprice);
                  $("#currtime").val(obj.currtime);
                  $("#prevclose").val(obj.prevclose);
              });

              mpost();
          },
          error: function (xhr, ajaxOptions, thrownError) {
             // alert('GET failed.');
          }

      });

        }



        function mpost()
        {
            $.ajax(
     {

         type: 'POST',
         url: "/OnlineCMOTSApi/GetBSEData/",
         data: { lname: $('#lname').val(), currprice: $('#currprice').val(), currtime:$('#currtime').val(), prevclose:$('#prevclose').val() },
         success: function (response) {

         },
         error: function (xhr, ajaxOptions, thrownError) {
           //  alert('Post failed.');
         }

     });
        }
    });



    </script>
}

KR_Choksey/Views/OnlineCMOTSApi/GetBSEGroupList.cshtml
@{
    ViewBag.Title = "GetBSEGroupList";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>GetBSEGroupList</h2>

@using (Html.BeginForm("GetBSEGroupList", "OnlineCMOTSApi", FormMethod.Post, new { @class = "form-horizontal", role = "form", enctype = "multipart/form-data" }))
{


    <div class="row">

        <input type="text" id="Mobile" name="Mobile" />

    </div>




    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/Scripts/jquery-1.10.2.js"></script>

    <script type="text/javascript">
    $(document).ready(function () {

        myFunc();

        function myFunc() {


            $.ajax(
      {
          type: 'GET',
          url: "http://krchokseyapi.cmlinks.com/Equity/Equity.svc/Group-List/bse",
          data: { responsetype: "json" },
          success: function (response)
          {
              //alert(response);
              var result = response.slice(78, -4);
              //alert(result);
              $("#Mobile").val(result);

              mpost(result);
              alert('Data Inserted');
          },
          error: function (xhr, ajaxOptions, thrownError) {
             // alert('GET failed.');
          }

      });

        }



        function mpost(result)
        {

            $.ajax(
     {

         type: 'POST',
         url: "/OnlineCMOTSApi/GetBSEGroupList/",
         //url: "/OnlineCMOTSApi/TestData/",
         data: {
             group: result
         },
         success: function (response) {

         },
         error: function (xhr, ajaxOptions, thrownError) {
           //  alert('Post failed.');
         }

     });
        }
    });



    </script>
}

KR_Choksey/Views/OnlineCMOTSApi/GetBSENetPriceLosersData.cshtml
@{
    ViewBag.Title = "GetBSENetPriceLosersData";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>GetBSENetPriceLosersData</h2>

@using (Html.BeginForm("GetBSENetPriceLosersData", "OnlineCMOTSApi", FormMethod.Post, new { @class = "form-horizontal", role = "form", enctype = "multipart/form-data" }))
{

    <div class="jumbotron">
        @*<h1>ASP.NET</h1>
            <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
            <p><a href="http://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>*@
    </div>

    <div class="row">

        <input type="text" id="Mobile" name="Mobile" />

        <input type="submit" id="Post" name="Post" />

        <input type="text" name="stk_exchange" id="stk_exchange" />
        <input type="text" name="sc_code" id="sc_code" />
        <input type="text" name="co_code" id="co_code" />
        <input type="text" name="symbol" id="symbol" />
        <input type="text" name="co_name" id="co_name" />
        <input type="text" name="sc_group" id="sc_group" />
        <input type="text" name="upd_time" id="upd_time" />
        <input type="text" name="open_price" id="open_price" />
        <input type="text" name="high_price" id="high_price" />
        <input type="text" name="low_price" id="low_price" />
        <input type="text" name="close_price" id="close_price" />
        <input type="text" name="bbuy_qty" id="bbuy_qty" />
        <input type="text" name="bbuy_price" id="bbuy_price" />
        <input type="text" name="bsell_qty" id="bsell_qty" />
        <input type="text" name="bsell_price" id="bsell_price" />
        <input type="text" name="prevclose" id="prevclose" />
        <input type="text" name="prevdate" id="prevdate" />
        <input type="text" name="perchg" id="perchg" />
        <input type="text" name="netchg" id="netchg" />
        <input type="text" name="vol_traded" id="vol_traded" />
        <input type="text" name="pervol" id="pervol" />
        <input type="text" name="val_traded" id="val_traded" />
        <input type="text" name="fiftytwoweekhigh" id="fiftytwoweekhigh" />
        <input type="text" name="fiftytwoweeklow" id="fiftytwoweeklow" />
        <input type="text" name="prev_vol_traded" id="prev_vol_traded" />
        <input type="text" name="prev_value_traded" id="prev_value_traded" />
        <input type="text" name="offerprice" id="offerprice" />
        <input type="text" name="offerqty" id="offerqty" />
        <input type="text" name="lname" id="lname" />

    </div>


    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/Scripts/jquery-1.10.2.js"></script>

    <script type="text/javascript">
    $(document).ready(function () {

        myFunc();

        function myFunc() {


            $.ajax(
      {
          type: 'GET',
          url: "http://krchokseyapi.cmlinks.com/Equity/Equity.svc/gainerslosers/bse/bse_sensex/lose/today/10",
          data: { responsetype: "json" },
          success: function (response) {
              //alert(response);
              var result = response.slice(82, -4);
              //alert(result);
              $("#Mobile").val(result);

              //$.each($.parseJSON(result), function (idx, obj)
              //{
              //    //alert(obj.bbuy_qty);
              //    //alert(obj.bbuy_price);
              //    $("#stk_exchange").val(obj.stk_exchange);
              //    $("#sc_code").val(obj.sc_code);
              //    $("#co_code").val(obj.co_code);
              //    $("#symbol").val(obj.symbol);
              //    $("#co_name").val(obj.co_name);
              //    $("#sc_group").val(obj.sc_group);
              //    $("#upd_time").val(obj.upd_time);
              //    $("#open_price").val(obj.open_price);
              //    $("#high_price").val(obj.high_price);
              //    $("#low_price").val(obj.low_price);
              //    $("#close_price").val(obj.close_price);
              //    $("#bbuy_qty").val(obj.bbuy_qty);
              //    $("#bbuy_price").val(obj.bbuy_price);
              //    $("#bsell_qty").val(obj.bsell_qty);
              //    $("#bsell_price").val(obj.bsell_price);
              //    $("#prevclose").val(obj.prevclose);
              //    $("#prevdate").val(obj.prevdate);
              //    $("#perchg").val(obj.perchg);
              //    $("#netchg").val(obj.netchg);
              //    $("#vol_traded").val(obj.vol_traded);
              //    $("#pervol").val(obj.pervol);
              //    $("#val_traded").val(obj.val_traded);
              //    $("#fiftytwoweekhigh").val(obj.fiftytwoweekhigh);
              //    $("#fiftytwoweeklow").val(obj.fiftytwoweeklow);
              //    $("#prev_vol_traded").val(obj.prev_vol_traded);
              //    $("#prev_value_traded").val(obj.prev_value_traded);
              //    $("#offerprice").val(obj.offerprice);
              //    $("#offerqty").val(obj.offerqty);
              //    $("#lname").val(obj.lname);

              //});

              mpost(result);
          },
          error: function (xhr, ajaxOptions, thrownError) {
             // alert('GET failed.');
          }

      });

        }

        function mpost(result) {
            $.ajax(
     {

         type: 'POST',
         url: "/OnlineCMOTSApi/GetBSENetPriceLosersData/",
         data:
             {
                 result1: result
             },
         success: function (response) {

         },
         error: function (xhr, ajaxOptions, thrownError) {
             //  alert('Post failed.');
         }

     });
        }

     //   function mpost()
     //   {
     //       $.ajax(
     //{

     //    type: 'POST',
     //    url: "/OnlineCMOTSApi/GetBSENetPriceLosersData/",
     //    data:
     //        {
     //            stk_exchange: $('#stk_exchange').val(),
     //            sc_code: $("#sc_code").val(),
     //            co_code: $("#co_code").val(),
     //           symbol: $("#symbol").val(),
     //           co_name: $("#co_name").val(),
     //           sc_group: $("#sc_group").val(),
     //           upd_time: $("#upd_time").val(),
     //           open_price: $("#open_price").val(),
     //           high_price: $("#high_price").val(),
     //           low_price: $("#low_price").val(),
     //           close_price: $("#close_price").val(),
     //           bbuy_qty: $("#bbuy_qty").val(),
     //           bbuy_price: $("#bbuy_price").val(),
     //           bsell_qty: $("#bsell_qty").val(),
     //           bsell_price: $("#bsell_price").val(),
     //           prevclose: $("#prevclose").val(),
     //           prevdate: $("#prevdate").val(),
     //           perchg: $("#perchg").val(),
     //           netchg: $("#netchg").val(),
     //           vol_traded: $("#vol_traded").val(),
     //           pervol: $("#pervol").val(),
     //           val_traded: $("#val_traded").val(),
     //           fiftytwoweekhigh: $("#fiftytwoweekhigh").val(),
     //           fiftytwoweeklow: $("#fiftytwoweeklow").val(),
     //           prev_vol_traded: $("#prev_vol_traded").val(),
     //           prev_value_traded: $("#prev_value_traded").val(),
     //           offerprice: $("#offerprice").val(),
     //           offerqty: $("#offerqty").val(),
     //           lname: $("#lname").val()
     //        },
     //    success: function (response) {

     //    },
     //    error: function (xhr, ajaxOptions, thrownError) {
     //      //  alert('Post failed.');
     //    }

     //});
     //   }
    });



    </script>
}

KR_Choksey/Views/OnlineCMOTSApi/GetCmotsBoardOfDirectors.cshtml
@model IEnumerable<KR_Choksey.Models.CmotsCompanyMaster>
@{
    ViewBag.Title = "GetCmotsBoardOfDirectors";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<script src="~/Scripts/jquery-1.10.2.min.js"></script>
<script src="~/Scripts/jquery-1.10.2.js"></script>

<h2>GetCmotsBoardOfDirectors</h2>

@using (Html.BeginForm("GetCmotsNSEQuoteDetails", "OnlineCMOTSApi", FormMethod.Post, new { @class = "form-horizontal", role = "form", enctype = "multipart/form-data" }))
{

    <div class="jumbotron">
        @*<h1>ASP.NET</h1>
            <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
            <p><a href="http://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>*@
    </div>

    <div class="row">

        <input type="text" id="CompanyDetails" name="CompanyDetails" />

        <input type="submit" id="Post" name="Post" />

        @foreach (var item in Model)
        {
            <script type="text/javascript">

                var urldata = "http://krchokseyapi.cmlinks.com/Company-Information/Company-Info.svc/boardOfdirectors/@item.co_code";
                var co_code=@item.co_code;
                JK(urldata,co_code)
                function JK(urldata,co_code) {

                    //$('#CompanyDetails').val(co_code);
                    //alert(urldata);

                    $.ajax(
              {
                  type: 'GET',
                  url: urldata,
                  data: { responsetype: "json" },
                  success: function (response) {
                      //alert(response);
                      var result = response.slice(99, -4);
                      //alert(result);
                      // $("#CompanyDetails").val(result);


                      mpost(result, co_code);
                      sleep(50000);
                  },
                  error: function (xhr, ajaxOptions, thrownError) {
                      // alert('GET failed.');
                  }

              });


                }

                function sleep(milliseconds) {
                    var start = new Date().getTime();
                    for (var i = 0; i < 1e7; i++) {
                        if ((new Date().getTime() - start) > milliseconds) {
                            break;
                        }
                    }
                }


                function mpost(result,co_code) {
                    $.ajax(
             {

                 type: 'POST',
                 url: "/OnlineCMOTSApi/GetCmotsBoardOfDirectors/",
                 data:
                     {
                         group: result,
                         comp_code:co_code
                     },
                 success: function (response) {

                 },
                 error: function (xhr, ajaxOptions, thrownError) {
                     //  alert('Post failed.');
                 }

             });
                }


            </script>
        }

    </div>


}

KR_Choksey/Views/OnlineCMOTSApi/GetCmotsCompanyChart1D.cshtml
@model IEnumerable<KR_Choksey.Models.CmotsCompanyMaster>
@{
    ViewBag.Title = "GetCmotsCompanyChart1D";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<script src="~/Scripts/jquery-1.10.2.min.js"></script>
<script src="~/Scripts/jquery-1.10.2.js"></script>

<h2>GetCmotsCompanyChart1D</h2>

@using (Html.BeginForm("GetCmotsCompanyChart1D", "OnlineCMOTSApi", FormMethod.Post, new { @class = "form-horizontal", role = "form", enctype = "multipart/form-data" }))
{

    <div class="jumbotron">
        @*<h1>ASP.NET</h1>
            <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
            <p><a href="http://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>*@
    </div>

    <div class="row">

        <input type="text" id="CompanyDetails" name="CompanyDetails" />

        <input type="submit" id="Post" name="Post" />

        @foreach (var item in Model)
        {
            <script type="text/javascript">

                var urldata = "http://krchokseyapi.cmlinks.com/Company-Information/Company-Info.svc/companychart/@item.co_code/1D";
                var co_code=@item.co_code;
                JK(urldata,co_code)
                function JK(urldata,co_code) {

                    //$('#CompanyDetails').val(co_code);
                    //alert(urldata);

                    $.ajax(
              {
                  type: 'GET',
                  url: urldata,
                  data: { responsetype: "json" },
                  success: function (response) {
                      //alert(response);
                      var result = response.slice(96, -4);
                     // alert(result);
                      // $("#CompanyDetails").val(result);


                      mpost(result, co_code);
                      sleep(50000);
                  },
                  error: function (xhr, ajaxOptions, thrownError) {
                      // alert('GET failed.');
                  }

              });


                }

                function sleep(milliseconds) {
                    var start = new Date().getTime();
                    for (var i = 0; i < 1e7; i++) {
                        if ((new Date().getTime() - start) > milliseconds) {
                            break;
                        }
                    }
                }


                function mpost(result,co_code) {
                    $.ajax(
             {

                 type: 'POST',
                 url: "/OnlineCMOTSApi/GetCmotsCompanyChart1D/",
                 data:
                     {
                         group: result,
                         comp_code:co_code
                     },
                 success: function (response) {

                 },
                 error: function (xhr, ajaxOptions, thrownError) {
                     //  alert('Post failed.');
                 }

             });
                }


</script>
        }

    </div>


}

KR_Choksey/Views/OnlineCMOTSApi/GetCmotsCompanyChart3M.cshtml
@model IEnumerable<KR_Choksey.Models.CmotsCompanyMaster>
@{
    ViewBag.Title = "GetCmotsCompanyChart3M";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<script src="~/Scripts/jquery-1.10.2.min.js"></script>
<script src="~/Scripts/jquery-1.10.2.js"></script>

<h2>GetCmotsCompanyChart3M</h2>

@using (Html.BeginForm("GetCmotsCompanyChart3M", "OnlineCMOTSApi", FormMethod.Post, new { @class = "form-horizontal", role = "form", enctype = "multipart/form-data" }))
{

    <div class="jumbotron">
        @*<h1>ASP.NET</h1>
            <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
            <p><a href="http://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>*@
    </div>

    <div class="row">

        <input type="text" id="CompanyDetails" name="CompanyDetails" />

        <input type="submit" id="Post" name="Post" />

        @foreach (var item in Model)
        {
            <script type="text/javascript">

                var urldata = "http://krchokseyapi.cmlinks.com/Company-Information/Company-Info.svc/companychart/@item.co_code/3M";
                var co_code=@item.co_code;
                JK(urldata,co_code)
                function JK(urldata,co_code) {

                    //$('#CompanyDetails').val(co_code);
                    //alert(urldata);

                    $.ajax(
              {
                  type: 'GET',
                  url: urldata,
                  data: { responsetype: "json" },
                  success: function (response) {
                      //alert(response);
                      var result = response.slice(96, -4);
                     //  alert(result);
                      // $("#CompanyDetails").val(result);


                      mpost(result, co_code);
                      sleep(50000);
                  },
                  error: function (xhr, ajaxOptions, thrownError) {
                      // alert('GET failed.');
                  }

              });


                }

                function sleep(milliseconds) {
                    var start = new Date().getTime();
                    for (var i = 0; i < 1e7; i++) {
                        if ((new Date().getTime() - start) > milliseconds) {
                            break;
                        }
                    }
                }


                function mpost(result,co_code) {
                    $.ajax(
             {

                 type: 'POST',
                 url: "/OnlineCMOTSApi/GetCmotsCompanyChart3M/",
                 data:
                     {
                         group: result,
                         comp_code:co_code
                     },
                 success: function (response) {

                 },
                 error: function (xhr, ajaxOptions, thrownError) {
                     //  alert('Post failed.');
                 }

             });
                }


            </script>
        }

    </div>


}